/* Automatically generated by po2tbl.sed from gnupg.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Warning: using insecure memory!\n", 2},
  {"operation is not possible without initialized secure memory\n", 3},
  {"(you may have used the wrong program for this task)\n", 4},
  {"yes", 5},
  {"yY", 6},
  {"no", 7},
  {"nN", 8},
  {"quit", 9},
  {"qQ", 10},
  {"general error", 11},
  {"unknown packet type", 12},
  {"unknown version", 13},
  {"unknown pubkey algorithm", 14},
  {"unknown digest algorithm", 15},
  {"bad public key", 16},
  {"bad secret key", 17},
  {"bad signature", 18},
  {"checksum error", 19},
  {"bad passphrase", 20},
  {"public key not found", 21},
  {"unknown cipher algorithm", 22},
  {"can't open the keyring", 23},
  {"invalid packet", 24},
  {"invalid armor", 25},
  {"no such user id", 26},
  {"secret key not available", 27},
  {"wrong secret key used", 28},
  {"not supported", 29},
  {"bad key", 30},
  {"file read error", 31},
  {"file write error", 32},
  {"unknown compress algorithm", 33},
  {"file open error", 34},
  {"file create error", 35},
  {"invalid passphrase", 36},
  {"unimplemented pubkey algorithm", 37},
  {"unimplemented cipher algorithm", 38},
  {"unknown signature class", 39},
  {"trust database error", 40},
  {"bad MPI", 41},
  {"resource limit", 42},
  {"invalid keyring", 43},
  {"bad certificate", 44},
  {"malformed user id", 45},
  {"file close error", 46},
  {"file rename error", 47},
  {"file delete error", 48},
  {"unexpected data", 49},
  {"timestamp conflict", 50},
  {"unusable pubkey algorithm", 51},
  {"file exists", 52},
  {"weak key", 53},
  {"invalid argument", 54},
  {"bad URI", 55},
  {"unsupported URI", 56},
  {"network error", 57},
  {"not encrypted", 58},
  {"not processed", 59},
  {"unusable public key", 60},
  {"unusable secret key", 61},
  {"... this is a bug (%s:%d:%s)\n", 62},
  {"you found a bug ... (%s:%d)\n", 63},
  {"can't open `%s': %s\n", 64},
  {"can't stat `%s': %s\n", 65},
  {"`%s' is not a regular file - ignored\n", 66},
  {"note: random_seed file is empty\n", 67},
  {"warning: invalid size of random_seed file - not used\n", 68},
  {"can't read `%s': %s\n", 69},
  {"note: random_seed file not updated\n", 70},
  {"can't create `%s': %s\n", 71},
  {"can't write `%s': %s\n", 72},
  {"can't close `%s': %s\n", 73},
  {"too many random bits requested; the limit is %d\n", 74},
  {"WARNING: using insecure random number generator!!\n", 75},
  {"\
The random number generator is only a kludge to let\n\
it run - it is in no way a strong RNG!\n\
\n\
DON'T USE ANY DATA GENERATED BY THIS PROGRAM!!\n\
\n", 76},
  {"\
\n\
Not enough random bytes available.  Please do some other work to give\n\
the OS a chance to collect more entropy! (Need %d more bytes)\n", 77},
  {"\
@Commands:\n\
 ", 78},
  {"|[file]|make a signature", 79},
  {"|[file]|make a clear text signature", 80},
  {"make a detached signature", 81},
  {"encrypt data", 82},
  {"encryption only with symmetric cipher", 83},
  {"store only", 84},
  {"decrypt data (default)", 85},
  {"verify a signature", 86},
  {"list keys", 87},
  {"list keys and signatures", 88},
  {"check key signatures", 89},
  {"list keys and fingerprints", 90},
  {"list secret keys", 91},
  {"generate a new key pair", 92},
  {"remove key from the public keyring", 93},
  {"remove key from the secret keyring", 94},
  {"sign a key", 95},
  {"sign a key locally", 96},
  {"sign or edit a key", 97},
  {"generate a revocation certificate", 98},
  {"export keys", 99},
  {"export keys to a key server", 100},
  {"import keys from a key server", 101},
  {"import/merge keys", 102},
  {"list only the sequence of packets", 103},
  {"export the ownertrust values", 104},
  {"import ownertrust values", 105},
  {"update the trust database", 106},
  {"|[NAMES]|check the trust database", 107},
  {"fix a corrupted trust database", 108},
  {"De-Armor a file or stdin", 109},
  {"En-Armor a file or stdin", 110},
  {"|algo [files]|print message digests", 111},
  {"\
@\n\
Options:\n\
 ", 112},
  {"create ascii armored output", 113},
  {"|NAME|encrypt for NAME", 114},
  {"|NAME|use NAME as default recipient", 115},
  {"use the default key as default recipient", 116},
  {"use this user-id to sign or decrypt", 117},
  {"|N|set compress level N (0 disables)", 118},
  {"use canonical text mode", 119},
  {"use as output file", 120},
  {"verbose", 121},
  {"be somewhat more quiet", 122},
  {"don't use the terminal at all", 123},
  {"force v3 signatures", 124},
  {"always use a MDC for encryption", 125},
  {"do not make any changes", 126},
  {"use the gpg-agent", 127},
  {"batch mode: never ask", 128},
  {"assume yes on most questions", 129},
  {"assume no on most questions", 130},
  {"add this keyring to the list of keyrings", 131},
  {"add this secret keyring to the list", 132},
  {"|NAME|use NAME as default secret key", 133},
  {"|HOST|use this keyserver to lookup keys", 134},
  {"|NAME|set terminal charset to NAME", 135},
  {"read options from file", 136},
  {"|FD|write status info to this FD", 137},
  {"|KEYID|ulimately trust this key", 138},
  {"|FILE|load extension module FILE", 139},
  {"emulate the mode described in RFC1991", 140},
  {"set all packet, cipher and digest options to OpenPGP behavior", 141},
  {"|N|use passphrase mode N", 142},
  {"|NAME|use message digest algorithm NAME for passphrases", 143},
  {"|NAME|use cipher algorithm NAME for passphrases", 144},
  {"|NAME|use cipher algorithm NAME", 145},
  {"|NAME|use message digest algorithm NAME", 146},
  {"|N|use compress algorithm N", 147},
  {"throw keyid field of encrypted packets", 148},
  {"|NAME=VALUE|use this notation data", 149},
  {"\
@\n\
(See the man page for a complete listing of all commands and options)\n", 150},
  {"\
@\n\
Examples:\n\
\n\
 -se -r Bob [file]          sign and encrypt for user Bob\n\
 --clearsign [file]         make a clear text signature\n\
 --detach-sign [file]       make a detached signature\n\
 --list-keys [names]        show keys\n\
 --fingerprint [names]      show fingerprints\n", 151},
  {"Please report bugs to <gnupg-bugs@gnu.org>.\n", 152},
  {"Usage: gpg [options] [files] (-h for help)", 153},
  {"\
Syntax: gpg [options] [files]\n\
sign, check, encrypt or decrypt\n\
default operation depends on the input data\n", 154},
  {"\
\n\
Supported algorithms:\n", 155},
  {"usage: gpg [options] ", 156},
  {"conflicting commands\n", 157},
  {"NOTE: no default option file `%s'\n", 158},
  {"option file `%s': %s\n", 159},
  {"reading options from `%s'\n", 160},
  {"%s is not a valid character set\n", 161},
  {"WARNING: program may create a core file!\n", 162},
  {"NOTE: %s is not for normal use!\n", 163},
  {"%s not allowed with %s!\n", 164},
  {"%s makes no sense with %s!\n", 165},
  {"selected cipher algorithm is invalid\n", 166},
  {"selected digest algorithm is invalid\n", 167},
  {"the given policy URL is invalid\n", 168},
  {"compress algorithm must be in range %d..%d\n", 169},
  {"completes-needed must be greater than 0\n", 170},
  {"marginals-needed must be greater than 1\n", 171},
  {"max-cert-depth must be in range 1 to 255\n", 172},
  {"NOTE: simple S2K mode (0) is strongly discouraged\n", 173},
  {"invalid S2K mode; must be 0, 1 or 3\n", 174},
  {"failed to initialize the TrustDB: %s\n", 175},
  {"--store [filename]", 176},
  {"--symmetric [filename]", 177},
  {"--encrypt [filename]", 178},
  {"--sign [filename]", 179},
  {"--sign --encrypt [filename]", 180},
  {"--clearsign [filename]", 181},
  {"--decrypt [filename]", 182},
  {"--sign-key user-id", 183},
  {"--lsign-key user-id", 184},
  {"--edit-key user-id [commands]", 185},
  {"--delete-secret-key user-id", 186},
  {"--delete-key user-id", 187},
  {"--delete-secret-and-public-key user-id", 188},
  {"can't open %s: %s\n", 189},
  {"-k[v][v][v][c] [user-id] [keyring]", 190},
  {"dearmoring failed: %s\n", 191},
  {"enarmoring failed: %s\n", 192},
  {"invalid hash algorithm `%s'\n", 193},
  {"[filename]", 194},
  {"Go ahead and type your message ...\n", 195},
  {"can't open `%s'\n", 196},
  {"\
the first character of a notation name must be a letter or an underscore\n", 197},
  {"\
a notation name must have only letters, digits, dots or underscores and end \
with an '='\n", 198},
  {"dots in a notation name must be surrounded by other characters\n", 199},
  {"a notation value must not use any control characters\n", 200},
  {"armor: %s\n", 201},
  {"invalid armor header: ", 202},
  {"armor header: ", 203},
  {"invalid clearsig header\n", 204},
  {"nested clear text signatures\n", 205},
  {"invalid dash escaped line: ", 206},
  {"unexpected armor:", 207},
  {"invalid radix64 character %02x skipped\n", 208},
  {"premature eof (no CRC)\n", 209},
  {"premature eof (in CRC)\n", 210},
  {"malformed CRC\n", 211},
  {"CRC error; %06lx - %06lx\n", 212},
  {"premature eof (in Trailer)\n", 213},
  {"error in trailer line\n", 214},
  {"For info see http://www.gnupg.org", 215},
  {"no valid OpenPGP data found.\n", 216},
  {"invalid armor: line longer than %d characters\n", 217},
  {"\
quoted printable character in armor - probably a buggy MTA has been used\n", 218},
  {"             Fingerprint:", 219},
  {"Fingerprint:", 220},
  {"No reason specified", 221},
  {"Key is superseded", 222},
  {"Key has been compromised", 223},
  {"Key is no longer used", 224},
  {"User ID is no longer valid", 225},
  {"Reason for revocation: ", 226},
  {"Revocation comment: ", 227},
  {"sSmMqQ", 228},
  {"\
No trust value assigned to %lu:\n\
%4u%c/%08lX %s \"", 229},
  {"\
Please decide how far you trust this user to correctly\n\
verify other users' keys (by looking at passports,\n\
checking fingerprints from different sources...)?\n\
\n\
 1 = Don't know\n\
 2 = I do NOT trust\n\
 3 = I trust marginally\n\
 4 = I trust fully\n\
 s = please show me more information\n", 230},
  {" m = back to the main menu\n", 231},
  {" q = quit\n", 232},
  {"Your decision? ", 233},
  {"Certificates leading to an ultimately trusted key:\n", 234},
  {"\
Could not find a valid trust path to the key.  Let's see whether we\n\
can assign some missing owner trust values.\n\
\n", 235},
  {"\
No path leading to one of our keys found.\n\
\n", 236},
  {"\
No certificates with undefined trust found.\n\
\n", 237},
  {"\
No trust values changed.\n\
\n", 238},
  {"key %08lX: key has been revoked!\n", 239},
  {"Use this key anyway? ", 240},
  {"key %08lX: subkey has been revoked!\n", 241},
  {"%08lX: key has expired\n", 242},
  {"%08lX: no info to calculate a trust probability\n", 243},
  {"%08lX: We do NOT trust this key\n", 244},
  {"\
%08lX: It is not sure that this key really belongs to the owner\n\
but it is accepted anyway\n", 245},
  {"This key probably belongs to the owner\n", 246},
  {"This key belongs to us\n", 247},
  {"\
It is NOT certain that the key belongs to its owner.\n\
If you *really* know what you are doing, you may answer\n\
the next question with yes\n\
\n", 248},
  {"WARNING: Using untrusted key!\n", 249},
  {"WARNING: This key has been revoked by its owner!\n", 250},
  {"         This could mean that the signature is forgery.\n", 251},
  {"WARNING: This subkey has been revoked by its owner!\n", 252},
  {"Note: This key has expired!\n", 253},
  {"WARNING: This key is not certified with a trusted signature!\n", 254},
  {"\
         There is no indication that the signature belongs to the owner.\n", 255},
  {"WARNING: We do NOT trust this key!\n", 256},
  {"         The signature is probably a FORGERY.\n", 257},
  {"\
WARNING: This key is not certified with sufficiently trusted signatures!\n", 258},
  {"         It is not certain that the signature belongs to the owner.\n", 259},
  {"%s: skipped: %s\n", 260},
  {"%s: skipped: public key already present\n", 261},
  {"\
You did not specify a user ID. (you may use \"-r\")\n\
\n", 262},
  {"Enter the user ID: ", 263},
  {"No such user ID.\n", 264},
  {"skipped: public key already set as default recipient\n", 265},
  {"Public key is disabled.\n", 266},
  {"skipped: public key already set with --encrypt-to\n", 267},
  {"unknown default recipient `%s'\n", 268},
  {"%s: error checking key: %s\n", 269},
  {"%s: skipped: public key is disabled\n", 270},
  {"no valid addressees\n", 271},
  {"writing self signature\n", 272},
  {"writing key binding signature\n", 273},
  {"keysize invalid; using %u bits\n", 274},
  {"keysize rounded up to %u bits\n", 275},
  {"Please select what kind of key you want:\n", 276},
  {"   (%d) DSA and ElGamal (default)\n", 277},
  {"   (%d) DSA (sign only)\n", 278},
  {"   (%d) ElGamal (encrypt only)\n", 279},
  {"   (%d) ElGamal (sign and encrypt)\n", 280},
  {"   (%d) RSA (sign and encrypt)\n", 281},
  {"Your selection? ", 282},
  {"Do you really want to create a sign and encrypt key? ", 283},
  {"The use of this algorithm is deprecated - create anyway? ", 284},
  {"Invalid selection.\n", 285},
  {"\
About to generate a new %s keypair.\n\
              minimum keysize is  768 bits\n\
              default keysize is 1024 bits\n\
    highest suggested keysize is 2048 bits\n", 286},
  {"What keysize do you want? (1024) ", 287},
  {"DSA only allows keysizes from 512 to 1024\n", 288},
  {"keysize too small; 768 is smallest value allowed.\n", 289},
  {"keysize too small; 1024 is smallest value allowed for RSA.\n", 290},
  {"keysize too large; %d is largest value allowed.\n", 291},
  {"\
Keysizes larger than 2048 are not suggested because\n\
computations take REALLY long!\n", 292},
  {"Are you sure that you want this keysize? ", 293},
  {"\
Okay, but keep in mind that your monitor and keyboard radiation is also very \
vulnerable to attacks!\n", 294},
  {"Do you really need such a large keysize? ", 295},
  {"Requested keysize is %u bits\n", 296},
  {"rounded up to %u bits\n", 297},
  {"\
Please specify how long the key should be valid.\n\
         0 = key does not expire\n\
      <n>  = key expires in n days\n\
      <n>w = key expires in n weeks\n\
      <n>m = key expires in n months\n\
      <n>y = key expires in n years\n", 298},
  {"Key is valid for? (0) ", 299},
  {"invalid value\n", 300},
  {"Key does not expire at all\n", 301},
  {"Key expires at %s\n", 302},
  {"\
Your system can't display dates beyond 2038.\n\
However, it will be correctly handled up to 2106.\n", 303},
  {"Is this correct (y/n)? ", 304},
  {"\
\n\
You need a User-ID to identify your key; the software constructs the user \
id\n\
from Real Name, Comment and Email Address in this form:\n\
    \"Heinrich Heine (Der Dichter) <heinrichh@duesseldorf.de>\"\n\
\n", 305},
  {"Real name: ", 306},
  {"Invalid character in name\n", 307},
  {"Name may not start with a digit\n", 308},
  {"Name must be at least 5 characters long\n", 309},
  {"Email address: ", 310},
  {"Not a valid email address\n", 311},
  {"Comment: ", 312},
  {"Invalid character in comment\n", 313},
  {"You are using the `%s' character set.\n", 314},
  {"\
You selected this USER-ID:\n\
    \"%s\"\n\
\n", 315},
  {"Please don't put the email address into the real name or the comment\n", 316},
  {"NnCcEeOoQq", 317},
  {"Change (N)ame, (C)omment, (E)mail or (Q)uit? ", 318},
  {"Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? ", 319},
  {"Please correct the error first\n", 320},
  {"\
You need a Passphrase to protect your secret key.\n\
\n", 321},
  {"passphrase not correctly repeated; try again.\n", 322},
  {"\
You don't want a passphrase - this is probably a *bad* idea!\n\
I will do it anyway.  You can change your passphrase at any time,\n\
using this program with the option \"--edit-key\".\n\
\n", 323},
  {"\
We need to generate a lot of random bytes. It is a good idea to perform\n\
some other action (type on the keyboard, move the mouse, utilize the\n\
disks) during the prime generation; this gives the random number\n\
generator a better chance to gain enough entropy.\n", 324},
  {"DSA keypair will have 1024 bits.\n", 325},
  {"Key generation canceled.\n", 326},
  {"writing public key to `%s'\n", 327},
  {"writing secret key to `%s'\n", 328},
  {"public and secret key created and signed.\n", 329},
  {"\
Note that this key cannot be used for encryption.  You may want to use\n\
the command \"--edit-key\" to generate a secondary key for this purpose.\n", 330},
  {"Key generation failed: %s\n", 331},
  {"\
key has been created %lu second in future (time warp or clock problem)\n", 332},
  {"\
key has been created %lu seconds in future (time warp or clock problem)\n", 333},
  {"Really create? ", 334},
  {"%s: can't open: %s\n", 335},
  {"error creating passphrase: %s\n", 336},
  {"%s: WARNING: empty file\n", 337},
  {"reading from `%s'\n", 338},
  {"%s/%s encrypted for: %s\n", 339},
  {"%s: user not found: %s\n", 340},
  {"certificate read problem: %s\n", 341},
  {"key %08lX: not a rfc2440 key - skipped\n", 342},
  {"key %08lX: not protected - skipped\n", 343},
  {"WARNING: nothing exported\n", 344},
  {"too many entries in pk cache - disabled\n", 345},
  {"[User id not found]", 346},
  {"too many entries in unk cache - disabled\n", 347},
  {"using secondary key %08lX instead of primary key %08lX\n", 348},
  {"key %08lX: secret key without public key - skipped\n", 349},
  {"skipping block of type %d\n", 350},
  {"%lu keys so far processed\n", 351},
  {"error reading `%s': %s\n", 352},
  {"Total number processed: %lu\n", 353},
  {"      skipped new keys: %lu\n", 354},
  {"          w/o user IDs: %lu\n", 355},
  {"              imported: %lu", 356},
  {"             unchanged: %lu\n", 357},
  {"          new user IDs: %lu\n", 358},
  {"           new subkeys: %lu\n", 359},
  {"        new signatures: %lu\n", 360},
  {"   new key revocations: %lu\n", 361},
  {"      secret keys read: %lu\n", 362},
  {"  secret keys imported: %lu\n", 363},
  {" secret keys unchanged: %lu\n", 364},
  {"key %08lX: no user ID\n", 365},
  {"key %08lX: no valid user IDs\n", 366},
  {"this may be caused by a missing self-signature\n", 367},
  {"key %08lX: public key not found: %s\n", 368},
  {"key %08lX: new key - skipped\n", 369},
  {"no default public keyring\n", 370},
  {"writing to `%s'\n", 371},
  {"can't lock keyring `%s': %s\n", 372},
  {"error writing keyring `%s': %s\n", 373},
  {"key %08lX: public key imported\n", 374},
  {"key %08lX: doesn't match our copy\n", 375},
  {"key %08lX: can't locate original keyblock: %s\n", 376},
  {"key %08lX: can't read original keyblock: %s\n", 377},
  {"key %08lX: 1 new user ID\n", 378},
  {"key %08lX: %d new user IDs\n", 379},
  {"key %08lX: 1 new signature\n", 380},
  {"key %08lX: %d new signatures\n", 381},
  {"key %08lX: 1 new subkey\n", 382},
  {"key %08lX: %d new subkeys\n", 383},
  {"key %08lX: not changed\n", 384},
  {"secret key %08lX not imported (use %s to allow for it)\n", 385},
  {"key %08lX: secret key imported\n", 386},
  {"key %08lX: already in secret keyring\n", 387},
  {"key %08lX: secret key not found: %s\n", 388},
  {"key %08lX: no public key - can't apply revocation certificate\n", 389},
  {"key %08lX: invalid revocation certificate: %s - rejected\n", 390},
  {"key %08lX: revocation certificate imported\n", 391},
  {"key %08lX: no user ID for signature\n", 392},
  {"key %08lX: unsupported public key algorithm\n", 393},
  {"key %08lX: invalid self-signature\n", 394},
  {"key %08lX: no subkey for key binding\n", 395},
  {"key %08lX: invalid subkey binding\n", 396},
  {"key %08lX: accepted non self-signed user ID '", 397},
  {"key %08lX: skipped user ID '", 398},
  {"key %08lX: skipped subkey\n", 399},
  {"key %08lX: non exportable signature (class %02x) - skipped\n", 400},
  {"key %08lX: revocation certificate at wrong place - skipped\n", 401},
  {"key %08lX: invalid revocation certificate: %s - skipped\n", 402},
  {"key %08lX: duplicated user ID detected - merged\n", 403},
  {"key %08lX: revocation certificate added\n", 404},
  {"key %08lX: our copy has no self-signature\n", 405},
  {"%s: user not found\n", 406},
  {"[revocation]", 407},
  {"[self-signature]", 408},
  {"1 bad signature\n", 409},
  {"%d bad signatures\n", 410},
  {"1 signature not checked due to a missing key\n", 411},
  {"%d signatures not checked due to missing keys\n", 412},
  {"1 signature not checked due to an error\n", 413},
  {"%d signatures not checked due to errors\n", 414},
  {"1 user ID without valid self-signature detected\n", 415},
  {"%d user IDs without valid self-signatures detected\n", 416},
  {"Already signed by key %08lX\n", 417},
  {"Nothing to sign with key %08lX\n", 418},
  {"\
Are you really sure that you want to sign this key\n\
with your key: \"", 419},
  {"\
The signature will be marked as non-exportable.\n\
\n", 420},
  {"Really sign? ", 421},
  {"signing failed: %s\n", 422},
  {"This key is not protected.\n", 423},
  {"Secret parts of primary key are not available.\n", 424},
  {"Key is protected.\n", 425},
  {"Can't edit this key: %s\n", 426},
  {"\
Enter the new passphrase for this secret key.\n\
\n", 427},
  {"\
You don't want a passphrase - this is probably a *bad* idea!\n\
\n", 428},
  {"Do you really want to do this? ", 429},
  {"moving a key signature to the correct place\n", 430},
  {"quit this menu", 431},
  {"q", 432},
  {"save", 433},
  {"save and quit", 434},
  {"help", 435},
  {"show this help", 436},
  {"fpr", 437},
  {"show fingerprint", 438},
  {"list", 439},
  {"list key and user IDs", 440},
  {"l", 441},
  {"uid", 442},
  {"select user ID N", 443},
  {"key", 444},
  {"select secondary key N", 445},
  {"check", 446},
  {"list signatures", 447},
  {"c", 448},
  {"sign", 449},
  {"sign the key", 450},
  {"s", 451},
  {"lsign", 452},
  {"sign the key locally", 453},
  {"debug", 454},
  {"adduid", 455},
  {"add a user ID", 456},
  {"deluid", 457},
  {"delete user ID", 458},
  {"addkey", 459},
  {"add a secondary key", 460},
  {"delkey", 461},
  {"delete a secondary key", 462},
  {"delsig", 463},
  {"delete signatures", 464},
  {"expire", 465},
  {"change the expire date", 466},
  {"toggle", 467},
  {"toggle between secret and public key listing", 468},
  {"t", 469},
  {"pref", 470},
  {"list preferences", 471},
  {"showpref", 472},
  {"passwd", 473},
  {"change the passphrase", 474},
  {"trust", 475},
  {"change the ownertrust", 476},
  {"revsig", 477},
  {"revoke signatures", 478},
  {"revkey", 479},
  {"revoke a secondary key", 480},
  {"disable", 481},
  {"disable a key", 482},
  {"enable", 483},
  {"enable a key", 484},
  {"can't do that in batchmode\n", 485},
  {"Secret key is available.\n", 486},
  {"Command> ", 487},
  {"Need the secret key to do this.\n", 488},
  {"Please use the command \"toggle\" first.\n", 489},
  {"Really sign all user IDs? ", 490},
  {"Hint: Select the user IDs to sign\n", 491},
  {"update of trustdb failed: %s\n", 492},
  {"You must select at least one user ID.\n", 493},
  {"You can't delete the last user ID!\n", 494},
  {"Really remove all selected user IDs? ", 495},
  {"Really remove this user ID? ", 496},
  {"You must select at least one key.\n", 497},
  {"Do you really want to delete the selected keys? ", 498},
  {"Do you really want to delete this key? ", 499},
  {"Do you really want to revoke the selected keys? ", 500},
  {"Do you really want to revoke this key? ", 501},
  {"Save changes? ", 502},
  {"Quit without saving? ", 503},
  {"update failed: %s\n", 504},
  {"update secret failed: %s\n", 505},
  {"Key not changed so no update needed.\n", 506},
  {"Invalid command  (try \"help\")\n", 507},
  {"%s%c %4u%c/%08lX  created: %s expires: %s", 508},
  {" trust: %c/%c", 509},
  {"This key has been disabled", 510},
  {"rev! subkey has been revoked: %s\n", 511},
  {"rev- faked revocation found\n", 512},
  {"rev? problem checking revocation: %s\n", 513},
  {"Delete this good signature? (y/N/q)", 514},
  {"Delete this invalid signature? (y/N/q)", 515},
  {"Delete this unknown signature? (y/N/q)", 516},
  {"Really delete this self-signature? (y/N)", 517},
  {"Deleted %d signature.\n", 518},
  {"Deleted %d signatures.\n", 519},
  {"Nothing deleted.\n", 520},
  {"Please remove selections from the secret keys.\n", 521},
  {"Please select at most one secondary key.\n", 522},
  {"Changing expiration time for a secondary key.\n", 523},
  {"Changing expiration time for the primary key.\n", 524},
  {"You can't change the expiration date of a v3 key\n", 525},
  {"No corresponding signature in secret ring\n", 526},
  {"No user ID with index %d\n", 527},
  {"No secondary key with index %d\n", 528},
  {"user ID: \"", 529},
  {"\
\"\n\
signed with your key %08lX at %s\n", 530},
  {"Create a revocation certificate for this signature? (y/N)", 531},
  {"You have signed these user IDs:\n", 532},
  {"   signed by %08lX at %s\n", 533},
  {"   revoked by %08lX at %s\n", 534},
  {"You are about to revoke these signatures:\n", 535},
  {"Really create the revocation certificates? (y/N)", 536},
  {"no secret key\n", 537},
  {" [expires: %s]", 538},
  {"public key is %08lX\n", 539},
  {"public key encrypted data: good DEK\n", 540},
  {"encrypted with %u-bit %s key, ID %08lX, created %s\n", 541},
  {"encrypted with %s key, ID %08lX\n", 542},
  {"public key decryption failed: %s\n", 543},
  {"decryption okay\n", 544},
  {"WARNING: encrypted message has been manipulated!\n", 545},
  {"decryption failed: %s\n", 546},
  {"NOTE: sender requested \"for-your-eyes-only\"\n", 547},
  {"original file name='%.*s'\n", 548},
  {"standalone revocation - use \"gpg --import\" to apply\n", 549},
  {"WARNING: invalid notation data found\n", 550},
  {"Notation: ", 551},
  {"Policy: ", 552},
  {"signature verification suppressed\n", 553},
  {"can't handle these multiple signatures\n", 554},
  {"Signature made %.*s using %s key ID %08lX\n", 555},
  {"BAD signature from \"", 556},
  {"Good signature from \"", 557},
  {"                aka \"", 558},
  {"Can't check signature: %s\n", 559},
  {"not a detached signature\n", 560},
  {"standalone signature of class 0x%02x\n", 561},
  {"old style (PGP 2.x) signature\n", 562},
  {"invalid root packet detected in proc_tree()\n", 563},
  {"can't disable core dumps: %s\n", 564},
  {"Experimental algorithms should not be used!\n", 565},
  {"this cipher algorithm is deprecated; please use a more standard one!\n", 566},
  {"can't handle public key algorithm %d\n", 567},
  {"subpacket of type %d has critical bit set\n", 568},
  {"gpg-agent is not available in this session\n", 569},
  {"malformed GPG_AGENT_INFO environment variable\n", 570},
  {"can't connect to `%s': %s\n", 571},
  {" (main key ID %08lX)", 572},
  {"\
You need a passphrase to unlock the secret key for user:\n\
\"%.*s\"\n\
%u-bit %s key, ID %08lX, created %s%s\n", 573},
  {"Enter passphrase\n", 574},
  {"Repeat passphrase\n", 575},
  {"passphrase too long\n", 576},
  {"invalid response from agent\n", 577},
  {"cancelled by user\n", 578},
  {"problem with the agent: agent returns 0x%lx\n", 579},
  {"\
\n\
You need a passphrase to unlock the secret key for\n\
user: \"", 580},
  {"%u-bit %s key, ID %08lX, created %s", 581},
  {"can't query password in batchmode\n", 582},
  {"Enter passphrase: ", 583},
  {"Repeat passphrase: ", 584},
  {"data not saved; use option \"--output\" to save it\n", 585},
  {"Detached signature.\n", 586},
  {"Please enter name of data file: ", 587},
  {"reading stdin ...\n", 588},
  {"no signed data\n", 589},
  {"can't open signed data `%s'\n", 590},
  {"anonymous receiver; trying secret key %08lX ...\n", 591},
  {"okay, we are the anonymous recipient.\n", 592},
  {"old encoding of the DEK is not supported\n", 593},
  {"cipher algorithm %d is unknown or disabled\n", 594},
  {"NOTE: cipher algorithm %d not found in preferences\n", 595},
  {"NOTE: secret key %08lX expired at %s\n", 596},
  {"requesting key %08lX from %s ...\n", 597},
  {"can't get key from keyserver: %s\n", 598},
  {"no keyserver known (use option --keyserver)\n", 599},
  {"%s: not a valid key ID\n", 600},
  {"error sending to `%s': %s\n", 601},
  {"success sending to `%s' (status=%u)\n", 602},
  {"failed sending to `%s': status=%u\n", 603},
  {"secret key parts are not available\n", 604},
  {"protection algorithm %d is not supported\n", 605},
  {"Invalid passphrase; please try again ...\n", 606},
  {"WARNING: Weak key detected - please change passphrase again.\n", 607},
  {"assuming bad MDC due to an unknown critical bit\n", 608},
  {"\
this is a PGP generated ElGamal key which is NOT secure for signatures!\n", 609},
  {"public key is %lu second newer than the signature\n", 610},
  {"public key is %lu seconds newer than the signature\n", 611},
  {"NOTE: signature key %08lX expired %s\n", 612},
  {"assuming bad signature due to an unknown critical bit\n", 613},
  {"checking created signature failed: %s\n", 614},
  {"%s signature from: %s\n", 615},
  {"can't create %s: %s\n", 616},
  {"signing:", 617},
  {"WARNING: `%s' is an empty file\n", 618},
  {"can't handle text lines longer than %d characters\n", 619},
  {"input line longer than %d characters\n", 620},
  {"trustdb rec %lu: lseek failed: %s\n", 621},
  {"trustdb rec %lu: write failed (n=%d): %s\n", 622},
  {"trustdb transaction too large\n", 623},
  {"%s: can't access: %s\n", 624},
  {"%s: directory does not exist!\n", 625},
  {"%s: can't create: %s\n", 626},
  {"%s: can't create lock\n", 627},
  {"%s: failed to create version record: %s", 628},
  {"%s: invalid trustdb created\n", 629},
  {"%s: trustdb created\n", 630},
  {"%s: invalid trustdb\n", 631},
  {"%s: failed to create hashtable: %s\n", 632},
  {"%s: error updating version record: %s\n", 633},
  {"%s: error reading version record: %s\n", 634},
  {"%s: error writing version record: %s\n", 635},
  {"trustdb: lseek failed: %s\n", 636},
  {"trustdb: read failed (n=%d): %s\n", 637},
  {"%s: not a trustdb file\n", 638},
  {"%s: version record with recnum %lu\n", 639},
  {"%s: invalid file version %d\n", 640},
  {"%s: error reading free record: %s\n", 641},
  {"%s: error writing dir record: %s\n", 642},
  {"%s: failed to zero a record: %s\n", 643},
  {"%s: failed to append a record: %s\n", 644},
  {"the trustdb is corrupted; please run \"gpg --fix-trustdb\".\n", 645},
  {"trust record %lu, req type %d: read failed: %s\n", 646},
  {"trust record %lu, type %d: write failed: %s\n", 647},
  {"trust record %lu: delete failed: %s\n", 648},
  {"trustdb: sync failed: %s\n", 649},
  {"error reading dir record for LID %lu: %s\n", 650},
  {"lid %lu: expected dir record, got type %d\n", 651},
  {"no primary key for LID %lu\n", 652},
  {"error reading primary key for LID %lu: %s\n", 653},
  {"get_dir_record: search_record failed: %s\n", 654},
  {"'%s' is not a valid long keyID\n", 655},
  {"key %08lX: can't put it into the trustdb\n", 656},
  {"key %08lX: query record failed\n", 657},
  {"key %08lX: already in trusted key table\n", 658},
  {"key %08lX: accepted as trusted key.\n", 659},
  {"key %08lX: no public key for trusted key - skipped\n", 660},
  {"NOTE: secret key %08lX is NOT protected.\n", 661},
  {"key %08lX: secret and public key don't match\n", 662},
  {"enumerate secret keys failed: %s\n", 663},
  {"key %08lX.%lu: Good subkey binding\n", 664},
  {"key %08lX.%lu: Invalid subkey binding: %s\n", 665},
  {"key %08lX.%lu: Valid key revocation\n", 666},
  {"key %08lX.%lu: Invalid key revocation: %s\n", 667},
  {"key %08lX.%lu: Valid subkey revocation\n", 668},
  {"Good self-signature", 669},
  {"Invalid self-signature", 670},
  {"Valid user ID revocation skipped due to a newer self signature", 671},
  {"Valid user ID revocation", 672},
  {"Invalid user ID revocation", 673},
  {"Valid certificate revocation", 674},
  {"Good certificate", 675},
  {"Invalid certificate revocation", 676},
  {"Invalid certificate", 677},
  {"sig record %lu[%d] points to wrong record.\n", 678},
  {"duplicated certificate - deleted", 679},
  {"tdbio_search_dir failed: %s\n", 680},
  {"lid ?: insert failed: %s\n", 681},
  {"lid %lu: insert failed: %s\n", 682},
  {"lid %lu: inserted\n", 683},
  {"error reading dir record: %s\n", 684},
  {"%lu keys processed\n", 685},
  {"\t%lu keys with errors\n", 686},
  {"\t%lu keys inserted\n", 687},
  {"enumerate keyblocks failed: %s\n", 688},
  {"lid %lu: dir record w/o key - skipped\n", 689},
  {"\t%lu due to new pubkeys\n", 690},
  {"\t%lu keys skipped\n", 691},
  {"\t%lu keys updated\n", 692},
  {"Ooops, no keys\n", 693},
  {"Ooops, no user IDs\n", 694},
  {"check_trust: search dir record failed: %s\n", 695},
  {"key %08lX: insert trust record failed: %s\n", 696},
  {"key %08lX.%lu: inserted into trustdb\n", 697},
  {"key %08lX.%lu: created in future (time warp or clock problem)\n", 698},
  {"key %08lX.%lu: expired at %s\n", 699},
  {"key %08lX.%lu: trust check failed: %s\n", 700},
  {"user '%s' not found: %s\n", 701},
  {"problem finding '%s' in trustdb: %s\n", 702},
  {"user '%s' not in trustdb - inserting\n", 703},
  {"failed to put '%s' into trustdb: %s\n", 704},
  {"WARNING: can't yet handle long pref records\n", 705},
  {"\
the signature could not be verified.\n\
Please remember that the signature file (.sig or .asc)\n\
should be the first file given on the command line.\n", 706},
  {"input line %u too long or missing LF\n", 707},
  {"%s: can't create keyring: %s\n", 708},
  {"%s: keyring created\n", 709},
  {"WARNING: 2 files with confidential information exists.\n", 710},
  {"%s is the unchanged one\n", 711},
  {"%s is the new one\n", 712},
  {"Please fix this possible security flaw\n", 713},
  {"key is not flagged as insecure - can't use it with the faked RNG!\n", 714},
  {"skipped `%s': duplicated\n", 715},
  {"skipped `%s': %s\n", 716},
  {"skipped: secret key already present\n", 717},
  {"\
skipped `%s': this is a PGP generated ElGamal key which is not secure for \
signatures!\n", 718},
  {"File `%s' exists. ", 719},
  {"Overwrite (y/N)? ", 720},
  {"%s: unknown suffix\n", 721},
  {"Enter new filename", 722},
  {"writing to stdout\n", 723},
  {"assuming signed data in `%s'\n", 724},
  {"%s: new options file created\n", 725},
  {"%s: can't create directory: %s\n", 726},
  {"%s: directory created\n", 727},
  {"you have to start GnuPG again, so it can read the new options file\n", 728},
  {"%s encrypted data\n", 729},
  {"encrypted with unknown algorithm %d\n", 730},
  {"\
WARNING: message was encrypted with a weak key in the symmetric cipher.\n", 731},
  {"problem handling encrypted packet\n", 732},
  {"weak key created - retrying\n", 733},
  {"cannot avoid weak key for symmetric cipher; tried %d times!\n", 734},
  {"can't do that in batchmode without \"--yes\"\n", 735},
  {"Delete this key from the keyring? ", 736},
  {"This is a secret key! - really delete? ", 737},
  {"there is a secret key for this public key!\n", 738},
  {"use option \"--delete-secret-key\" to delete it first.\n", 739},
  {"\
It's up to you to assign a value here; this value will never be exported\n\
to any 3rd party.  We need it to implement the web-of-trust; it has nothing\n\
to do with the (implicitly created) web-of-certificates.", 740},
  {"If you want to use this revoked key anyway, answer \"yes\".", 741},
  {"If you want to use this untrusted key anyway, answer \"yes\".", 742},
  {"\
Enter the user ID of the addressee to whom you want to send the message.", 743},
  {"\
Select the algorithm to use.\n\
\n\
DSA (aka DSS) is the digital signature algorithm which can only be used\n\
for signatures.  This is the suggested algorithm because verification of\n\
DSA signatures are much faster than those of ElGamal.\n\
\n\
ElGamal is an algorithm which can be used for signatures and encryption.\n\
OpenPGP distinguishs between two flavors of this algorithms: an encrypt \
only\n\
and a sign+encrypt; actually it is the same, but some parameters must be\n\
selected in a special way to create a safe key for signatures: this program\n\
does this but other OpenPGP implementations are not required to understand\n\
the signature+encryption flavor.\n\
\n\
The first (primary) key must always be a key which is capable of signing;\n\
this is the reason why the encryption only ElGamal key is not available in\n\
this menu.", 744},
  {"\
Although these keys are defined in RFC2440 they are not suggested\n\
because they are not supported by all programs and signatures created\n\
with them are quite large and very slow to verify.", 745},
  {"Enter the size of the key", 746},
  {"Answer \"yes\" or \"no\"", 747},
  {"\
Enter the required value as shown in the prompt.\n\
It is possible to enter a ISO date (YYYY-MM-DD) but you won't\n\
get a good error response - instead the system tries to interpret\n\
the given value as an interval.", 748},
  {"Enter the name of the key holder", 749},
  {"please enter an optional but highly suggested email address", 750},
  {"Please enter an optional comment", 751},
  {"\
N  to change the name.\n\
C  to change the comment.\n\
E  to change the email address.\n\
O  to continue with key generation.\n\
Q  to to quit the key generation.", 752},
  {"Answer \"yes\" (or just \"y\") if it is okay to generate the sub key.", 753},
  {"Answer \"yes\" is you want to sign ALL the user IDs", 754},
  {"\
Answer \"yes\" if you really want to delete this user ID.\n\
All certificates are then also lost!", 755},
  {"Answer \"yes\" if it is okay to delete the subkey", 756},
  {"\
This is a valid signature on the key; you normally don't want\n\
to delete this signature because it may be important to establish a\n\
trust connection to the key or another key certified by this key.", 757},
  {"\
This signature can't be checked because you don't have the\n\
corresponding key.  You should postpone its deletion until you\n\
know which key was used because this signing key might establish\n\
a trust connection through another already certified key.", 758},
  {"\
The signature is not valid.  It does make sense to remove it from\n\
your keyring.", 759},
  {"\
This is a signature which binds the user ID to the key. It is\n\
usually not a good idea to remove such a signature.  Actually\n\
GnuPG might not be able to use this key anymore.  So do this\n\
only if this self-signature is for some reason not valid and\n\
a second one is available.", 760},
  {"\
Please enter the passhrase; this is a secret sentence \n\
  Blurb, blurb,.... ", 761},
  {"Please repeat the last passphrase, so you are sure what you typed in.", 762},
  {"Give the name of the file to which the signature applies", 763},
  {"Answer \"yes\" if it is okay to overwrite the file", 764},
  {"\
Please enter a new filename. If you just hit RETURN the default\n\
file (which is shown in brackets) will be used.", 765},
  {"\
You should specify a reason for the certification.  Depending on the\n\
context you have the ability to choose from this list:\n\
  \"Key has been compromised\"\n\
      Use this if you have a reason to believe that unauthorized persons\n\
      got access to your secret key.\n\
  \"Key is superseded\"\n\
      Use this if you have replaced this key with a newer one.\n\
  \"Key is no longer used\"\n\
      Use this if you have retired this key.\n\
  \"User ID is no longer valid\"\n\
      Use this to state that the user ID should not longer be used;\n\
      this is normally used to mark an email address invalid.\n", 766},
  {"\
If you like, you can enter a text describing why you issue this\n\
revocation certificate.  Please keep this text concise.\n\
An empty line ends the text.\n", 767},
  {"No help available", 768},
  {"No help available for `%s'", 769},
};

int _msg_tbl_length = 769;
